//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIT420Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int SongID { get; set; }
        public string SongTitle { get; set; }
        public Nullable<float> NonBandMemberWriters { get; set; }
        public Nullable<float> Danceability { get; set; }
        public Nullable<float> Duration { get; set; }
        public Nullable<float> Energy { get; set; }
        public string Explicit { get; set; }
        public string Popularity { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public Nullable<int> AlbumID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
    }
}
