//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIT420Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorldHealth
    {
        public int HealthID { get; set; }
        public string CountryName { get; set; }
        public Nullable<long> Year { get; set; }
        public Nullable<double> LogGdpPerCapita { get; set; }
        public Nullable<double> SocialSupport { get; set; }
        public Nullable<double> HealthyLifeExpectancyAtBirth { get; set; }
        public Nullable<double> FreedomToMakeLifeChoices { get; set; }
        public Nullable<double> Generosity { get; set; }
        public Nullable<double> PerceptionsOfCorruption { get; set; }
        public Nullable<double> PositiveEffect { get; set; }
        public Nullable<double> NegativeEffect { get; set; }
    }
}
